### ISSUE TITLE
gobackup must support endpoint-url parameter when using Minio as S3 backend

### ISSUE THREAD

**Issue by schakko** [NeosIT/gobackup#1]
To make gobackup work with Minio backends, the *endpoint-url* parameter. When *endpoint-url* is used, the region must not be set.

TODOs:
- add *ctx.Endpoint = aws.String(ctx.viper.GetString("endpoint"))* in https://github.com/huacnlee/gobackup/blob/master/storage/s3.go as described in https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
- update documentation at (https://gobackup.github.io/configuration/storages/s3/ btw: link on the page points to scp.go and not to s3.go) 
- Test against Minio
- PR for main repo

**Comment by thomashoell** [comment]
This is already supported
