### ISSUE TITLE
gobackup must support forcePathStyle when using Minio as S3 backend

### ISSUE THREAD

**Issue by schakko** [NeosIT/gobackup#2]
When Minio is used, the option S3ForcePathStyle (https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config) must be configurable and enabled. The option is required in our environment as we don't use host-based (e.g. bucket.minio.domain.tld) buckets due to our Kubernetes environment. Instead, access to the bucket has to be peformed by using the path (minio.domain.tld/bucket).

- add ctx.S3ForcePathStyle = aws.String(ctx.viper.GetBoolean("forcePathStyle")) in https://github.com/huacnlee/gobackup/blob/master/storage/s3.go as described in https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
- update documentation at (https://gobackup.github.io/configuration/storages/s3/)
- Test against Minio
- PR for main repo

**Comment by neos-it-user** [comment]
See https://github.com/NeosIT/gobackup/commit/7267a70d5658c99890f520410a5588e77a815104
